### ISSUE TITLE
Help converting to Java 

### ISSUE THREAD

**Issue by hiwa-jalal** [wasabeef/recyclerview-animators#177]
can someone please help me converting these line of code to Java

`val recyclerView = findViewById<RecyclerView>(R.id.list)
recyclerView.itemAnimator = SlideInLeftAnimator()`

**Comment by Baraka1Ahmad** [comment]
```
RecyclerView recyclerView  = findViewById(R.id.list);
recyclerView.setItemAnimator(new SlideInLeftAnimator());
```
