### ISSUE TITLE
No animation when using with cursor

### ISSUE THREAD

**Issue by tinmegali** [wasabeef/recyclerview-animators#33]
Hello,
First of all, this is a really nice project and initiative. **Congrats!**
I tested with using an ArrayList as Dataset and worked just fine. But when I tried to implement in my project, where I use a cursor as data,  no animation played (except the adapter animation, with was a little buggy).
I don't know if is a problem, but I'm just notifying the adapter with: notifyDataSetChanged()

**RecyclerView Declaration and setup:**
    
    // Cursor Adapter  
     recyclerAdapterDetail   = new DetailTaskRecyclerAdapter( getActivity(), null );
     recyclerViewDetail      = (RecyclerView)       fragmentView.findViewById(R.id.fragment_detail_recyclerview);

      LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getActivity());
      linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);

      recyclerViewDetail.setItemAnimator(new FadeInAnimator());
      recyclerViewDetail.getItemAnimator().setAddDuration( 1000 );
      recyclerViewDetail.setLayoutManager(linearLayoutManager);

      recyclerViewDetail.setAdapter( recyclerAdapterDetail );

**Notifying part on the adapter:**

    public Cursor swapCursor(Cursor cursor) {
        if (this.cursor == cursor) {
            return null;
        }
        Cursor oldCursor = this.cursor;
        this.cursor = cursor;
        if (cursor != null) {
            this.notifyDataSetChanged();
        }
        return oldCursor;
    }

**Comment by craya1982** [comment]
From https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#notifyDataSetChanged()   : 
This event does not specify what about the data set has changed, forcing any observers to assume that all existing items and structure may no longer be valid. LayoutManagers will be forced to fully rebind and relayout all visible views.


You should be using notifyitemchanged/notifyiteminserted/etc with Recyclerviews

**Comment by wasabeef** [comment]
@tinmegali  

Please use the following  
`notifyItemChanged(int)`
`notifyItemInserted(int)`
`notifyItemRemoved(int)`
`notifyItemRangeChanged(int, int)`
`notifyItemRangeInserted(int, int)`
`notifyItemRangeRemoved(int, int)`

If you want your animations to work, do not rely on calling `notifyDataSetChanged()`; 
as it is the RecyclerView's default behavior, animations are not triggered to start inside this method.

**Comment by junior201110** [comment]
thanks for help me


2016-02-21 15:40 GMT-03:00 Tin Megali <notifications@github.com>:

> Closed #33 <https://github.com/wasabeef/recyclerview-animators/issues/33>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wasabeef/recyclerview-animators/issues/33#event-558554895>
> .
>



-- 
*junior201110>>>*
