### ISSUE TITLE
latest JAR is lose efficacy URL

### ISSUE THREAD

**Issue by my9074** [wasabeef/recyclerview-animators#37]
Download the latest JAR is only 200+Byte sizes

**Comment by wasabeef** [comment]
@my9074 

Hi

please retry.
https://search.maven.org/remote_content?g=jp.wasabeef&a=recyclerview-animators&v=LATEST

**Comment by wasabeef** [comment]
@my9074 

Hi. 
How do?

```groovy
compile 'jp.wasabeef:recyclerview-animators:1.2.3'
```
