### ISSUE TITLE
Warning:Module version jp.wasabeef:recyclerview-animators:1.2.2 depends on libraries but is a jar

### ISSUE THREAD

**Issue by JesseBlackman** [wasabeef/recyclerview-animators#39]
Warning:Module version jp.wasabeef:recyclerview-animators:1.2.2 depends on libraries but is a jar

**Comment by wasabeef** [comment]
@JesseBlackman 

oh.. Please retry..
```groovy
compile 'jp.wasabeef:recyclerview-animators:1.2.3'
```

**Comment by JesseBlackman** [comment]
still doesn't work
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find jp.wasabeef:recyclerview-animators:1.2.3.
     Searched in the following locations:
         https://repo1.maven.org/maven2/jp/wasabeef/recyclerview-animators/1.2.3/recyclerview-animators-1.2.3.pom
         https://repo1.maven.org/maven2/jp/wasabeef/recyclerview-animators/1.2.3/recyclerview-animators-1.2.3.jar
         file:/Users/leigang/Library/Android/sdk/extras/android/m2repository/jp/wasabeef/recyclerview-animators/1.2.3/recyclerview-animators-1.2.3.pom
         file:/Users/leigang/Library/Android/sdk/extras/android/m2repository/jp/wasabeef/recyclerview-animators/1.2.3/recyclerview-animators-1.2.3.jar
         file:/Users/leigang/Library/Android/sdk/extras/google/m2repository/jp/wasabeef/recyclerview-animators/1.2.3/recyclerview-animators-1.2.3.pom
         file:/Users/leigang/Library/Android/sdk/extras/google/m2repository/jp/wasabeef/recyclerview-animators/1.2.3/recyclerview-animators-1.2.3.jar
     Required by:
         sohuautonews:app:unspecified

allprojects {
    repositories {
       mavenCentral()
      // jcenter()
    }
}
in my project build.gradle file.May it cause this problem?

**Comment by wasabeef** [comment]
@JesseBlackman 

Please add `jcenter()`

**Comment by JesseBlackman** [comment]
@wasabeef 
is this library request minSdkVersion is 11?
my work must include sdk version 10...

**Comment by wasabeef** [comment]
@JesseBlackman 

Yes, because it uses the [Animator](http://developer.android.com/intl/ja/reference/android/animation/Animator.html)

**Comment by akashk92** [comment]
Error:(47, 13) Failed to resolve: jp.wasabeef:recyclerview-animators:1.3.0
Show in File
Show in Project Structure dialog
