### ISSUE TITLE
BREAKING CHANGES in revision 23.1.0 of Android Support Library

### ISSUE THREAD

**Issue by ygnessin** [wasabeef/recyclerview-animators#47]
[Revision 23.1.0 of the Android Support Library](https://developer.android.com/intl/ko/tools/support-library/index.html#revisions) includes the following updates:

> Added an improved animation API to the ItemAnimator class for better customizations:
 - Change animations no longer enforce two copies of the ViewHolder object, which enables item content animations. Also, the ItemAnimator object decides whether it wants to reuse the same ViewHolder object or create a new one.
 - The new information record API gives the ItemAnimator class the flexibility to collect data at the correct point in the layout lifecycle. This information is later passed into the animate callbacks.
 - Provided an easy transition plan for this backward-incompatible API change:

> If you’ve previously extended the `ItemAnimator` class, you can change your base class to `SimpleItemAnimator` and your code should work as before. The `SimpleItemAnimator` class provides the old API by wrapping the new API.

> Some methods were removed from the `ItemAnimator` class. The following code will no longer compile:

> ```java
recyclerView.getItemAnimator().setSupportsChangeAnimations(false)
```
> You can replace it with:

> ```java
ItemAnimator animator = recyclerView.getItemAnimator();
if (animator instanceof SimpleItemAnimator) {
   ((SimpleItemAnimator) animator).setSupportsChangeAnimations(false);
}
```

In my project I am using Proguard, and with the new revision of the support library there are these warnings:

```
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator: can't find referenced method 'void dispatchMoveFinished(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator: can't find referenced method 'void dispatchChangeFinished(android.support.v7.widget.RecyclerView$ViewHolder,boolean)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator: can't find referenced method 'void dispatchRemoveFinished(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator: can't find referenced method 'void dispatchAddFinished(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$4: can't find referenced method 'void dispatchMoveStarting(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$4: can't find referenced method 'void dispatchMoveFinished(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$5: can't find referenced method 'void dispatchChangeStarting(android.support.v7.widget.RecyclerView$ViewHolder,boolean)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$5: can't find referenced method 'void dispatchChangeFinished(android.support.v7.widget.RecyclerView$ViewHolder,boolean)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$6: can't find referenced method 'void dispatchChangeStarting(android.support.v7.widget.RecyclerView$ViewHolder,boolean)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$6: can't find referenced method 'void dispatchChangeFinished(android.support.v7.widget.RecyclerView$ViewHolder,boolean)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$DefaultAddVpaListener: can't find referenced method 'void dispatchAddStarting(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$DefaultAddVpaListener: can't find referenced method 'void dispatchAddFinished(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$DefaultRemoveVpaListener: can't find referenced method 'void dispatchRemoveStarting(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
Warning:jp.wasabeef.recyclerview.animators.BaseItemAnimator$DefaultRemoveVpaListener: can't find referenced method 'void dispatchRemoveFinished(android.support.v7.widget.RecyclerView$ViewHolder)' in program class jp.wasabeef.recyclerview.animators.BaseItemAnimator
```
Indeed, if I ignore these warnings, it causes a crash in my app. Please fix, thank you!

**Comment by lawloretienne** [comment]
I get this crash after updating the support library

java.lang.AbstractMethodError: abstract method "boolean android.support.v7.widget.RecyclerView$ItemAnimator.animateAppearance(android.support.v7.widget.RecyclerView$ViewHolder, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo)"
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3037)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.access$800(RecyclerView.java:144)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:421)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:213)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2931)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.View.layout(View.java:16630)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5437)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
10-15 18:10:04.420 1125-1125/com.etiennelawlor.loop E/AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRoot

**Comment by wasabeef** [comment]
@ygnessin @lawloretienne 

Thanks.
I try it.

**Comment by craya1982** [comment]
What device and version of Android are you running? There's an issue with the new support library on Samsung 4.2.1

**Comment by wasabeef** [comment]
@ygnessin @lawloretienne @craya1982 

v2.0.0 has been released. (**if you use a 23.1.0 or higher**)

**Comment by ygnessin** [comment]
Thanks for the quick response!

**Comment by sander-m** [comment]
After updating to 23.1.0 support library and v2.0.0, change-animations do not work anymore. There used to be a nice fade animation when changing the content of an item, i.e. when calling the `RecyclerView.Adapter` method `notifyItemChanged(index)`.

**Comment by wasabeef** [comment]
@sander-m 

https://github.com/wasabeef/recyclerview-animators/issues/50
