### ISSUE TITLE
Not scrolling to first item after doing animation

### ISSUE THREAD

**Issue by elsennov** [wasabeef/recyclerview-animators#94]
Hi, i have a problem while removing then inserting item in recycler view with the animation. So, after removed and inserted, the top position visible is the 2nd item. So, i cannot see the new first item instantly.
Here is my code
`// Remove from its position
conversations.remove(position);
notifyItemRemoved(position);

// Move to first position
conversations.add(Constants.FIRST, conversation);
notifyItemInserted(Constants.FIRST);`

**Comment by kvipul** [comment]
any update to this?? I'm also facing the same issue!!
